settings:
  files:
    outputs:
      status: false
    logs:
      status: false
    errors:
      status: false
  legacy:
    force: false
    interval: 0s
server:
    status: true
    open: false
    host: 0.0.0.0
    port: 8088
schema:
- name: route53-ddns
  path: .
  commands:
    vet:
      status: true
    fmt:
      status: true
    test:
      status: true
    build:
      method: make build
      args:
      - -o bin/route53-ddns
        ./cmd/route53-ddns/main.go
      status: true
    run:
      status: false
      method: ./bin/route53-ddns -h
  watcher:
    extensions:
    - go
    paths:
    - /
